apiVersion: v1
kind: Service
metadata:
  name: app-b
  namespace: default
  labels:
    app: app-b
spec:
  type: ClusterIP
  selector:
    app: app-b
  ports:
  - name: https
    port: 8443
    targetPort: 8443
    protocol: TCP
