server:
  port: 8443
  ssl:
    enabled: true
    key-store: file:/etc/security/ssl/app-a-keystore.p12
    key-store-password: ${ssl.keystore-password}
    key-store-type: ${ssl.keystore-type}
    key-alias: ${ssl.key-alias}
    trust-store: file:/etc/security/ssl/truststore.jks
    trust-store-password: ${ssl.truststore-password}
    trust-store-type: ${ssl.truststore-type}
    client-auth: need

spring:
  application:
    name: app-a

app:
  b:
    url: https://app-b.default.svc.cluster.local:8443

logging:
  level:
    com.k8s.appa: DEBUG
    org.springframework.web: INFO
    org.apache.http: DEBUG
    org.springframework.cloud.vault: DEBUG
