server:
  port: 8443
  ssl:
    enabled: true
    key-store: file:/etc/security/ssl/app-a-keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: app-a
    trust-store: file:/etc/security/ssl/truststore.jks
    trust-store-password: changeit
    trust-store-type: JKS
    client-auth: need

spring:
  application:
    name: app-a

app:
  b:
    url: https://app-b.default.svc.cluster.local:8443

logging:
  level:
    com.k8s.appa: DEBUG
    org.springframework.web: INFO
    org.apache.http: DEBUG
    org.springframework.cloud.vault: DEBUG
    org.springframework.boot.autoconfigure.ssl: DEBUG
    org.springframework.boot.web.embedded.tomcat: DEBUG
    org.springframework.context: DEBUG
    org.springframework.core.env: TRACE
