name: CI - Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build and Test Maven Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean verify -B

    - name: Run tests
      run: mvn test -B

    - name: Build app-a module
      run: mvn package -pl app-a -B

    - name: Build app-b module
      run: mvn package -pl app-b -B

    - name: Upload app-a artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-a-jar
        path: app-a/target/*.jar
        retention-days: 5

    - name: Upload app-b artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-b-jar
        path: app-b/target/*.jar
        retention-days: 5

  build-docker-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build Maven artifacts
      run: mvn clean package -DskipTests -B

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build App A Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: k8s/Dockerfile-app-a
        push: false
        tags: app-a:1.0.0-SNAPSHOT
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build App B Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: k8s/Dockerfile-app-b
        push: false
        tags: app-b:1.0.0-SNAPSHOT
        cache-from: type=gha
        cache-to: type=gha,mode=max

  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Run Maven verify
      run: mvn verify -B

    - name: Check for TODO/FIXME comments
      run: |
        if grep -r "TODO\|FIXME" app-a/src app-b/src 2>/dev/null; then
          echo "Found TODO/FIXME comments - consider addressing them"
        fi
      continue-on-error: true
